# AO ALTERAR ISSO REINICIE O SERVIDOR #
Armazenamento:
  Tipo: "SQLITE" # Aqui, você pode habilitar o MYSql ("MYSQL") ou deixar então SQLITE ("SQLITE")

  # DESCONSIDERAR CASO USE "SQLITE" ACIMA
  url: "localhost"
  port: 3306
  user: "root"
  pass: "password"
  database: "Guerreiro"

AutoStart:
  Horarios:
    - "10:00"
    - "13:00"
    - "17:00"
    - "20:00"

Config:
  Language: "pt-br"
  Minimo-Participantes: 2 # Aqui você coloca o minimo de participantes pro evento não ser cancelado
  Tag: "&2[Guerreiro]"
  Itens: "&a&lGUERREIRO" # Todos os itens virão com esse nome
  Premio: 25000.0
  Win-Commands: # comandos ao executar quando o evento terminar (APÓS O DELAY DO FIM DO EVENTO)
    - "say {player} venceu o evento!"
    - "say {player} venceu o evento!"
  Formatar-Premio: true # "true" para formatar o prêmio ao anunciar a vitória (exmplo: 25K, 25M, 25B, 25T, 25Q)
  Tempo-Anuncios: 60 # Tempo que vai ficar anunciando
  Tempo-Entre: 10 # Tempo entre cada anuncio
  Tempo-Espera: 10 # Tempo de espera para os players se prepararem antes de ativar o PVP (MINIMO 10)
  Tempo-Final: 10 # Tempo que vai demorar para teleportar o vencedor para a saida do evento
  Abate-Geral: true # Coloque "true" para enviar para todos do servidor quando alguem morrer no evento, ou então "false" para que a mensagem de morte só seja entregue para os participantes do evento.
  Chat: false # "true" para deixar o chat liberado dentro do evento, e "false" para deixar o chat bloqueado pra quem ta dentro do evento
  Dropar-Itens: false # "true" para deixar o drop de itens liberado dentro do evento, "false" para deixar o drop bloqueado.
  Executar-Comandos: false # "true" para deixar os comandos liberados dentro do evento, "false" para deixar os comandos bloqueados (EXCETO OS COMANDOS DO EVENTO, /guerreiro sair, status, etc...).

  Ranking-Limit: 5 # Coloque aqui qual limite de jogadores que podem aparecer no top

  Deathmatch:
    Habilitado: true # "true" para ter deathmatch "false" para não ter
    Tempo: 900 # Tempo em segundos para iniciar o deathmatch (MINIMO 300)
    Sem-PvP: 10 # Tempo que vai ficar sem PVP ao puxar o deathmatch