name: BGGuerreiro
version: 1.1.4
main: me.zbrunooow.bgguerreiro.WarriorEngine
authors: [zBrunooow, sync]
description: Plugin of PvP event Warrior
depend: [Vault]
softdepend: [WorldGuard, Multiverse-Core, LegendChat, nChat, UltimateChat, SimpleClans]
commands:
  guerreiro:
    aliases: [bgguerreiro, guerrero, warrior]
    description: "General Command"